### ISSUE TITLE
Spark Save Modes , "overwrite" always drops table although "truncate" is true.

### ISSUE THREAD

**Issue by akifcakir** [exasol/spark-exasol-connector#99]
Hi Dear Team, 

I am trying to import data from databricks to Exasol DB.

I am using following code in below, 
dfw.write \
    .format("jdbc") \
    .option("driver", exa_driver) \
    .option("url", exa_url) \
    .option("dbtable", "table") \
    .option("user", username) \
    .option("password", exa_password) \
    .option("truncate", "true") \
    .option("numPartitions", "1") \
    .option("fetchsize", "100000") \
    .mode("overwrite") \
    .save()
 The problem is when mode is "overwrite", it always drop target table in Exasol db, although in the spark documentation (https://spark.apache.org/docs/3.0.1/sql-data-sources-jdbc.html#content) it says for "truncate" option that  

truncate --> This is a JDBC writer related option. When SaveMode.Overwrite is enabled, this option causes Spark to truncate an existing table instead of dropping and recreating it. This can be more efficient, and prevents the table metadata (e.g., indices) from being removed. However, it will not work in some cases, such as when the new data has a different schema. It defaults to false. This option applies only to writing.

 According to this explanation , I would expect with option("truncate", "true"), it should not drop but truncate the table. Nevertheless it drops the table even in that case. 

 Note: we can have separate truncate command and go with append mode but I do not want to have extra second command but solve in one command as suggested in Exasol documentation here (https://github.com/exasol/spark-exasol-connector/blob/main/doc/user_guide/user_guide.md#spark-save-modes) as well.

 Am I missing something or do you have any resolution ?

**Comment by morazow** [comment]
Hello @akifcakir,

Sorry for the late reply, we missed your question. 

Please be aware that the `spark-exasol-connector` works different than the Spark regular JDBC dialect. At the moment, [there is no Exasol dialect in the Spark](https://github.com/apache/spark/blob/master/sql/core/src/main/scala/org/apache/spark/sql/jdbc/JdbcDialects.scala#L416-L423), so it will use the generic dialect options.

I looked into the Spark codebase and the `truncate` option is [enabled when also the `isCascadingTruncate` set to false](https://github.com/apache/spark/blob/master/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/jdbc/JdbcRelationProvider.scala#L55). Could you please try with setting `cascadeTruncate` to false?

Additionally please give a try to `spark-exasol-connector` since it uses parallel subconnections.

**Comment by morazow** [comment]
Hello @akifcakir,

I am going to close the ticket for now. Please let us know if you have more questions.
